#!/bin/sh
set -eu
exec /app/op-batcher \
  --l2-eth-rpc=http://op-geth:8545 \
  --rollup-rpc=http://op-node:8547 \
  --poll-interval=10s \
  --sub-safety-margin=6 \
  --num-confirmations=1 \
  --safe-abort-nonce-too-low-count=3 \
  --resubmission-timeout=30s \
  --rpc.addr=0.0.0.0 \
  --rpc.port=8548 \
  --rpc.enable-admin \
  --max-channel-duration=6 \
  --l1-eth-rpc=$L1_RPC_URL \
  --private-key=$GS_BATCHER_PRIVATE_KEY \
  --altda.enabled="true" \
  --altda.da-service="false" \
  --altda.da-server=http://da-server:3100 

#  --altda.enabled="false" 
#  --altda.da-server="http://37.27.129.89:3100" \
#  --altda.da-service="true"
#  --altda.da-server=https://dcda-dev.dome.cloud
#  --data-availability-type=blobs \
#  --throttle-interval=0 \
