#!/bin/sh
set -eu
/app/geth --datadir /datadir init /config/genesis.json
exec /app/geth --datadir /datadir \
  --http \
  --http.corsdomain="*" \
  --http.vhosts="*" \
  --http.addr=0.0.0.0 \
  --http.api=web3,debug,eth,txpool,net,engine,miner \
  --ws \
  --ws.addr=0.0.0.0 \
  --ws.port=8546 \
  --ws.origins="*" \
  --ws.api=debug,eth,txpool,net,engine,miner \
  --syncmode=full \
  --networkid=$CHAIN_ID \
  --authrpc.vhosts="*" \
  --authrpc.addr=0.0.0.0 \
  --authrpc.port=8551 \
  --authrpc.jwtsecret=/config/jwt.txt \
  --db.engine=pebble \
  --nodiscover \
  --rollup.disabletxpoolgossip=true \
  --rpc.allow-unprotected-txs \
  --nodekeyhex=8a7c607deceb716e12c8af049eb3dac7a7434a903df2c6fe0703899433329eed \
  --port=30301

